In [17]:
student = {
    "name": "Ram",
    "age": 20,
    "faculty": "BCE"
}

In [7]:
!pip install pandas
import pandas as pd

Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (2.3.0)
Requirement already satisfied: numpy>=1.26.0 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/mrs/Library/Python/3.13/lib/python/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/mrs/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

ModuleNotFoundError: No module named 'pandas'

In [8]:
import sys
print(sys.executable)

/opt/homebrew/opt/python@3.10/bin/python3.10

In [9]:
import sys
!{sys.executable} -m pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp310-cp310-macosx_11_0_arm64.whl.metadata (91 kB)
Collecting numpy>=1.22.4 (from pandas)
  Downloading numpy-2.2.6-cp310-cp310-macosx_14_0_arm64.whl.metadata (62 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/mrs/Library/Python/3.10/lib/python/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Downloading pytz-2026.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in /Users/mrs/Library/Python/3.10/lib/python/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp310-cp310-macosx_11_0_arm64.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 22.8 MB/s eta 0:00:00 0:00:01
Downloading numpy-2.2.6-cp310-cp310-macosx_14_0_arm64.whl (5.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 27.1 MB/s eta 0:00:00
Downloading pytz-2026.2-py2.py3-none-any.whl (510 kB)
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [pandas]2m3/4 [pandas]
Successfully installed numpy-2.2.6 pandas-2.3.3 pytz-2026.2 tzdata-2026.2

[notice] A new release of pip is available: 25.1.1 -> 26.1.2
[notice] To update, run: /opt/homebrew/opt/python@3.10/bin/python3.10 -m pip install --upgrade pip

In [10]:
import pandas as pd
print(pd.__version__)

2.3.3

In [19]:
df = pd.DataFrame([student])

In [20]:
print(df)

  name  age faculty
0  Ram   20     BCE

In [21]:
df.head()

  name  age faculty
0  Ram   20     BCE

In [22]:
df.tail()

  name  age faculty
0  Ram   20     BCE

In [23]:
df.columns

Index(['name', 'age', 'faculty'], dtype='object')

In [24]:
df.sample

<bound method NDFrame.sample of   name  age faculty
0  Ram   20     BCE>

In [25]:
df.shape

(1, 3)

In [26]:
df['name']

0    Ram
Name: name, dtype: object

In [27]:
df.loc[0, 'name']

'Ram'

In [28]:
df['grade'] = 'A'

In [29]:
print(df)

  name  age faculty grade
0  Ram   20     BCE     A